version: '2.1'
services:
  image:
    extends:
      file: docker-compose-base.yml
      service: base-rabbitmq
    container_name: ${CONTAINER_HOST_NAME:-standalone.rabbitmq}
    environment:
    - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-admin}
    - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-admin_pass}
    hostname: ${CONTAINER_HOST_NAME:-standalone.rabbitmq}
    image: ${IMAGE_PREFIX:-cloudready/}${IMAGE_NAME:-rabbitmq}:${IMAGE_TAG:-3.7.7-management-alpine-SNAPSHOT}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.rabbitmq}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/rabbitmq/standalone}
    ports:
    - "${EXTERNAL_RABBITMQ_4369_PORT:-4369}:4369"
    - "${EXTERNAL_RABBITMQ_5671_PORT:-5671}:5671"
    - "${EXTERNAL_RABBITMQ_5672_PORT:-5672}:5672"
    - "${EXTERNAL_RABBITMQ_25672_PORT:-25672}:25672"
    # management ports
    - "${EXTERNAL_RABBITMQ_15671_PORT:-15671}:15671"
    - "${EXTERNAL_RABBITMQ_15672_PORT:-15672}:15672"
    restart: always
    volumes:
    - data:/var/lib/rabbitmq
    - log:/var/log/rabbitmq

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
  log:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/log
      o: bind
