version: '2.1'
services:
  image:
    extends:
      file: docker-compose-base.yml
      service: base-rabbitmq
    container_name: ${CONTAINER_HOST_NAME:-rabbitmq}
    environment:
    - RABBITMQ_USER=${RABBITMQ_USER:-admin}
    - RABBITMQ_PASS=${RABBITMQ_PASS:-admin_pass}
    hostname: ${CONTAINER_HOST_NAME:-rabbitmq}
    image: ${IMAGE_PREFIX:-cloudready}/${IMAGE_NAME:-rabbitmq}:${IMAGE_TAG:-3.7.7-management-alpine-SNAPSHOT}
    ports:
    - "${RABBITMQ_4369_PORT:-4369}:4369"
    - "${RABBITMQ_5671_PORT:-5671}:5671"
    - "${RABBITMQ_5672_PORT:-5672}:5672"
    - "${RABBITMQ_25672_PORT:-25672}:25672"
    # management ports
    - "${RABBITMQ_15671_PORT:-15671}:15671"
    - "${RABBITMQ_15672_PORT:-15672}:15672"
    volumes:
    - data:/var/lib/rabbitmq
    - log:/var/log/rabbitmq

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
  log:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/log
      o: bind
