version: '2.1'
services:
  rabbitmq377-m:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_PREFIX:-cirepo}/rabbitmq:${IMAGE_TAG:-3.7.7-management}
    container_name: ${INSTANCE_NAME:-rabbitmq377-m}.${INSTANCE_DOMAIN:-local}
    hostname: ${INSTANCE_NAME:-rabbitmq377-m}.${INSTANCE_DOMAIN:-local}
    networks:
      local-network:
        ipv4_address: 172.16.238.125
        ipv6_address: 2001:3984:3989::125
    ports:
    - "${RABBITMQ_4369_PORT:-4369}:4369"
    - "${RABBITMQ_5671_PORT:-5671}:5671"
    - "${RABBITMQ_5672_PORT:-5672}:5672"
    - "${RABBITMQ_25672_PORT:-25672}:25672"
    - "${RABBITMQ_15671_PORT:-15671}:15671"
    - "${RABBITMQ_15672_PORT:-15672}:15672"
    volumes:
    - data:/var/lib/rabbitmq

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      - subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind